<?php

use Schepeis\Mapping\Mapper;

class MapperTest extends \PHPUnit\Framework\TestCase
{
    protected Mapper $subject;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->subject = new Mapper();
        $this->subject->configure(new \Atomescrochus\StringSimilarities\Compare(), 'similarText');
    }

    public function testLevensteinComparison() {
        $result = $this->subject->map("Mercedes Benz", "Renault");

        $this->assertNull($result);

    }
}
